### ISSUE TITLE
No docker-yml exist

### ISSUE THREAD

**Issue by lion-rion** [jphacks/D_2203#5]
No docker-yml exist

plz make docker-compose.yml

```
version: '3.8'

services:
  database:
    image: mysql:8
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel_docker
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '4306:3306'
  php-apache:
    container_name: php-apache
    build:
      context: ./php
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/php_docker
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - database

```
